version: '3.8'

services:
  lab8_api:
    build:
      context: ./lab8/lab8
      dockerfile: Dockerfile
    container_name: lab8_api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    networks:
      - lab8_network

networks:
  lab8_network:
    driver: bridge
