version: '3.8'

services:
  app:
    build:
      dockerfile: rest_api/Dockerfile
      context: .
    container_name: myfirst_dockerized_rest_server
    ports:
      - "8000:80"
    volumes:
      - ./rest_api:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: myfirst_dockerized_database_server
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    volumes:
      - ./db_dumps/world.sql:/docker-entrypoint-initdb.d/world.sql
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  db_data: